In [ ]:
import torch
import numpy as np

list = ([1,2],[3,4],[5,6])
tensor1 = torch.tensor(list)
print("T1:", tensor1)

tensor2 = torch.tensor([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print("T2:", tensor2)

T1: tensor([[1, 2],
        [3, 4],
        [5, 6]])
T2: tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])


In [ ]:
print(tensor1.size())
print(tensor2.size())

torch.Size([3, 2])
torch.Size([2, 2, 3])


In [ ]:
print(tensor1[0])
print(tensor1[0,1])

tensor([1, 2])
tensor(2)


In [ ]:
x = torch.tensor([2],dtype=torch.float,requires_grad=True)
print(x)
y = x.pow(3)
print(y)
y.backward()
x.grad

tensor([2.], requires_grad=True)
tensor([8.], grad_fn=<PowBackward0>)


tensor([12.])

In [ ]:
%%time
for i in range(500):
  x = torch.randn(1000,1000)
  y = torch.randn(1000,1000)
  z = torch.matmul(x,y)

CPU times: user 24.3 s, sys: 109 ms, total: 24.4 s
Wall time: 24.3 s


In [ ]:
%%time
device = torch.device("cuda:0")
for i in range(500):
  x = torch.randn(1000,1000,device = device)
  y = torch.randn(1000,1000,device = device)
  z = torch.matmul(x,y)

RuntimeError: ignored